kind: Service
apiVersion: v1
metadata:
  name: blog-service
  namespace: production
spec:
  ports:
  - port: 80
    protocol: TCP
  #type: LoadBalancer
  selector:
    app: blog
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-deployment
  namespace: production
spec:
  selector:
    matchLabels:
      app: blog
  replicas: 2
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - name: php-blog
        image: farman17/aplikasi-blog
        ports:
          - containerPort: 80
       

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: blog-ingress
  namespace: production
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: blog.dailybugis.my.id
    http:
      paths:
      #- path: /
      - backend:
          serviceName: blog-service
          servicePort: 80

